require 'shellwords'

task default: ['server:cli']

namespace :cli do
  task tests: [:clean_up]

  task :test_cli do
    tests_file = File.join(__dir__, 'tc_cli.rb')
    ruby Shellwords.escape(tests_file)
  end

  task clean_up: [:test_cli] do
  end
end
