#!/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby --disable-gems

require 'shellwords'

if ARGV[0].nil?
  STDERR.puts 'Error no plugin name specified.'
  exit 1
end

plugin_name = ARGV[0]

dir = Dir.pwd

script_arg = File.join(__dir__, 'run_plugin.scpt')
command = "/usr/bin/osascript #{script_arg} #{Shellwords.escape(plugin_name)} #{Shellwords.escape(dir)}"

arguments = ARGV[1..-1]
command += ' ' + arguments.compact.map(&:to_s).map do |x|
  Shellwords.escape(x)
end.join(' ')

`#{command}`
